apiVersion: images.lab.gilman.io/v1alpha1
kind: ImageManifest
metadata:
  name: lab-images
spec:
  images:
    - name: vyos-stream
      source:
        url: https://community-downloads.vyos.dev/stream/2025.11/vyos-2025.11-generic-amd64.iso
        checksum: sha256:f60a2d7dd3bdf2e370a45c04ed4fc3b195691694ca3b8546adf4c5983e70d96e
      destination: vyos/vyos-2025.11-generic-amd64.iso
      hooks:
        preUpload:
          - name: vyos-integration-test
            command: ./images/hooks/vyos-test.sh
            timeout: 20m

    # Talos Linux ISOs
    # Base ISO: Vanilla Talos for general use (VMs, other nodes)
    - name: talos-base
      source:
        url: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.12.0/metal-amd64.iso
        checksum: sha256:862d7afc6b9f9c27033f5addf05f699b48be83aea81768349ae9a07b9e8eb8b5
      destination: talos/talos-1.12.0-metal-amd64.iso

    # UM760 ISO: Talos with embedded machine configuration for CP-1
    # The transform hook generates machine config via talhelper and embeds it
    # into the ISO using the Talos imager. This allows direct bootstrap without
    # a seed cluster serving configs over HTTP.
    - name: talos-um760
      source:
        # Note: The downloaded ISO is replaced entirely by the imager output.
        # We use the same base URL for consistency, but only the Talos version
        # from talconfig.yaml matters for the final ISO.
        url: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.12.0/metal-amd64.iso
        checksum: sha256:862d7afc6b9f9c27033f5addf05f699b48be83aea81768349ae9a07b9e8eb8b5
      destination: talos/talos-1.12.0-um760.iso
      hooks:
        transform:
          - name: embed-um760-config
            command: ./images/hooks/talos-embed-config.sh
            args: ["cp-1"]
            timeout: 10m
            # Declare input files that affect the transform output.
            # Changes to these files will trigger a re-sync.
            inputs:
              - "infrastructure/compute/talos/talconfig.yaml"
              - "infrastructure/compute/talos/talsecret.sops.yaml"
